# Semidefinite Programming https://www.cvxpy.org/examples/basic/sdp.html

In [1]:
import cvxpy as cp
import numpy as np

In [28]:
n = 3
p = 3
np.random.seed(1)
C = np.random.randn(n, n)
A = []
b = []
for i in range(p):
    A.append(np.random.randn(n, n))
    b.append(np.random.randn())
    
X = cp.Variable((n, n), symmetric=True)
constraints = [X >> 0]
constraints += [cp.trace(A[i] @ X) == b[i] for i in range(p)]
prob = cp.Problem(cp.Minimize(cp.trace(C @ X)), constraints)
prob.solve()

print('The status:', prob.status)
print('The optimal value is:', prob.value)
print('A solution X is\n', X.value)

The status: optimal
The optimal value is: 2.6543515102316015
A solution X is
 [[ 1.60805795 -0.59770492 -0.69576152]
 [-0.59770492  0.22229041  0.24689363]
 [-0.69576152  0.24689363  1.39679885]]


In [29]:
constraints

[PSD(Expression(AFFINE, UNKNOWN, (3, 3))),
 Equality(Expression(AFFINE, UNKNOWN, ()), Constant(CONSTANT, NONNEGATIVE, ())),
 Equality(Expression(AFFINE, UNKNOWN, ()), Constant(CONSTANT, NONPOSITIVE, ())),
 Equality(Expression(AFFINE, UNKNOWN, ()), Constant(CONSTANT, NONNEGATIVE, ()))]

In [30]:
X

Variable((3, 3), symmetric=True)

In [31]:
prob

Problem(Minimize(Expression(AFFINE, UNKNOWN, ())), [PSD(Expression(AFFINE, UNKNOWN, (3, 3))), Equality(Expression(AFFINE, UNKNOWN, ()), Constant(CONSTANT, NONNEGATIVE, ())), Equality(Expression(AFFINE, UNKNOWN, ()), Constant(CONSTANT, NONPOSITIVE, ())), Equality(Expression(AFFINE, UNKNOWN, ()), Constant(CONSTANT, NONNEGATIVE, ()))])

In [41]:
lst = [X, X]
sum(lst).value

array([[ 3.2161159 , -1.19540984, -1.39152305],
       [-1.19540984,  0.44458083,  0.49378725],
       [-1.39152305,  0.49378725,  2.79359769]])

In [64]:
lst = [X, X, X]
np.trace(sum(lst).value)

9.68144163219791

In [44]:
type(prob.status)

str

In [48]:
a = 1 + 0j

In [54]:
X.value

array([[ 1.60805795, -0.59770492, -0.69576152],
       [-0.59770492,  0.22229041,  0.24689363],
       [-0.69576152,  0.24689363,  1.39679885]])

In [52]:
cp.trace(X).value

array(3.22714721)

In [63]:
np.trace(X.value)

3.2271472107326367