In [16]:
import numpy as np
from scipy.linalg import sqrtm

In [29]:
vec1 = np.array([1, 0])
vec2 = np.array([1/np.sqrt(2), 1/np.sqrt(2)])

mat1 = np.outer(vec1, vec1)
mat2 = np.outer(vec2, vec2)

p = [0.5, 0.5]

In [25]:
rho = p[0]*mat1 + p[1]*mat2
rho

array([[0.75, 0.25],
       [0.25, 0.25]])

$a = rho^{1/2}$

In [26]:
a = sqrtm(rho)
a

array([[0.8446232 , 0.19134172],
       [0.19134172, 0.46193977]])

In [21]:
np.dot(a, a)

array([[0.75, 0.25],
       [0.25, 0.25]])

$b = a^{-1} = rho^{-1/2}$

In [27]:
b = np.linalg.inv(a)
b

array([[ 1.30656296, -0.5411961 ],
       [-0.5411961 ,  2.38895517]])

In [28]:
np.dot(a, b)

array([[ 1.00000000e+00, -3.00657824e-18],
       [-1.62927348e-17,  1.00000000e+00]])