# For a unitary matrix, its inverse equals to its conjugate transpose

In [4]:
import numpy as np
from qiskit.quantum_info import random_unitary

In [5]:
U = random_unitary(2)
U = U._data
U

array([[ 0.24761623-0.07348799j, -0.43119448+0.86449814j],
       [-0.85226531+0.4548951j , -0.0666244 +0.24955054j]])

In [6]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.24761623+0.07348799j, -0.85226531-0.4548951j ],
       [-0.43119448-0.86449814j, -0.0666244 -0.24955054j]])

In [12]:
U_ct = np.matrix(U).getH()
U_ct

matrix([[ 0.24761623+0.07348799j, -0.85226531-0.4548951j ],
        [-0.43119448-0.86449814j, -0.0666244 -0.24955054j]])

$U^{-1} = U^{\dagger} \Longrightarrow U^{-1} - U^{\dagger} = 0 $

In [15]:
U_inv - U_ct

matrix([[ 2.49800181e-16+5.55111512e-17j,
         -3.33066907e-16-1.66533454e-16j],
        [ 5.55111512e-17+1.11022302e-16j,
          1.38777878e-17+1.11022302e-16j]])