In [1]:
import numpy as np
from qiskit.quantum_info import random_unitary
from qiskit_textbook.tools import random_state

In [17]:
U = np.array([[0, 0.5], [0.5, 0]])

In [18]:
U_ct = U.conjugate().transpose()
U_ct

array([[0. , 0.5],
       [0.5, 0. ]])

In [19]:
U = np.array([[0, complex(0, -0.5)], [complex(0, 0.5), 0]])
U

array([[0.+0.j , 0.-0.5j],
       [0.+0.5j, 0.+0.j ]])

In [20]:
U_ct = U.conjugate().transpose()
U_ct

array([[0.-0.j , 0.-0.5j],
       [0.+0.5j, 0.-0.j ]])

# For a unitary matrix, $U^{-1} = U^{\dagger}$

In [21]:
seed = 1

In [22]:
U = random_unitary(2, seed=seed)
U = U._data
U

array([[ 0.29891817+0.78310097j,  0.06526452+0.54142529j],
       [ 0.28581644-0.46444565j, -0.59915425+0.58618545j]])

In [23]:
U_inv = np.linalg.inv(U)
U_inv

array([[ 0.29891817-0.78310097j,  0.28581644+0.46444565j],
       [ 0.06526452-0.54142529j, -0.59915425-0.58618545j]])

In [24]:
U_ct = np.matrix(U).getH()
U_ct

matrix([[ 0.29891817-0.78310097j,  0.28581644+0.46444565j],
        [ 0.06526452-0.54142529j, -0.59915425-0.58618545j]])

## $U^{-1} - U^{\dagger} = 0 $

In [27]:
U_inv - U_ct

matrix([[-1.24900090e-16-5.55111512e-17j,
          5.55111512e-17-2.22044605e-16j],
        [ 5.55111512e-17+2.22044605e-16j,
          6.93889390e-17-5.55111512e-17j]])

# For a unitary matrix, $\langle \psi| U \otimes U^{\dagger} |\psi\rangle = \langle \psi| U^{\dagger} \otimes U |\psi\rangle$

In [28]:
U = random_unitary(2, seed=seed)
U_ct = U.conjugate().transpose()
U_ct

Operator([[ 0.08093444+0.34481847j,  0.41224974-0.83940454j],
          [-0.41503551-0.83803065j,  0.0797887 -0.34508539j]],
         input_dims=(2,), output_dims=(2,))

In [29]:
UU_ct = U.tensor(U_ct)
U_ctU = U_ct.tensor(U)

In [88]:
def print_matrix(matrix):
    for row in matrix:
        for item in row:
            real = f'{item.real:.4f}'
            imag = f'{item.imag:.4f}'
            if imag[0] != '-':
                imag = '+' + imag
            print(f'({real:>7}{imag:>7}i)', end=' ')
        print()

In [89]:
print_matrix(UU_ct.data)

( 0.1255+0.0000i) (-0.2561-0.2101i) (-0.3226-0.0753i) ( 0.5323+0.6939i) 
(-0.3226+0.0753i) (-0.1125-0.0554i) ( 0.8745+0.0000i) ( 0.2561+0.2101i) 
(-0.2561+0.2101i) ( 0.8745+0.0000i) (-0.1125+0.0554i) ( 0.3226+0.0753i) 
( 0.5323-0.6939i) ( 0.3226-0.0753i) ( 0.2561-0.2101i) ( 0.1255+0.0000i) 


In [90]:
print_matrix(U_ctU.data)

( 0.1255+0.0000i) (-0.3226-0.0753i) (-0.2561-0.2101i) ( 0.5323+0.6939i) 
(-0.2561+0.2101i) (-0.1125+0.0554i) ( 0.8745+0.0000i) ( 0.3226+0.0753i) 
(-0.3226+0.0753i) ( 0.8745+0.0000i) (-0.1125-0.0554i) ( 0.2561+0.2101i) 
( 0.5323-0.6939i) ( 0.2561-0.2101i) ( 0.3226-0.0753i) ( 0.1255+0.0000i) 


In [106]:
vec = random_state(nqubits=2)

In [107]:
val = np.dot(np.dot(np.conj(vec), U_ctU.data), vec)
print(f'|<a|U_ct(tensor)U|a>| = {abs(val)}')

val = np.dot(np.dot(np.conj(vec), UU_ct.data), vec)
print(f'|<a|U(tensor)U_ct|a>| = {abs(val)}')

|<a|U_ct(tensor)U|a>| = 0.9162486792982869
|<a|U(tensor)U_ct|a>| = 0.9162486792982869
